# TODO: update production site config
title: PlayStation
description: >-
    PlayStation site design concept
url: 'https://bradypp.github.io/playstation/'
cover: 'https://bradypp.github.io/playstation/img/og.png'
icon: 'https://bradypp.github.io/playstation/img/favicon.ico'
name: 'PlayStation'

# Build settings
markdown: kramdown
destination: ./docs

# Exclude from processing.
exclude:
    - '.sass-cache'
    - '.jekyll-cache'
    - 'gemfiles'
    - 'Gemfile'
    - 'Gemfile.lock'
    - '*.gemspec'
    - 'README.md'
    - 'node_modules'
    - 'gulp-tasks'
    - 'gulpfile.babel.js'
    - 'yarn.lock'
    - 'package.json'

keep_files:
    - 'CNAME'
    - '.git'
    - '.gitignore'

plugins:
    - jekyll-minifier
    - jekyll-sitemap
