# TODO: update site config
title: PlayStation
description: >-
    PlayStation home page demo
baseurl: ''
url: ''
cover: domain/img/path
logo: domain/img/path

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
    - '.sass-cache'
    - '.jekyll-cache'
    - 'gemfiles'
    - 'Gemfile'
    - 'Gemfile.lock'
    - '*.gemspec'
    - 'README.md'
    - 'node_modules'
    - 'gulp-tasks'
    - 'gulpfile.babel.js'
    - 'yarn.lock'
    - 'package.json'

keep_files:
    - 'CNAME'
    - '.git'
    - '.gitignore'

plugins:
    - jekyll-minifier
    - jekyll-sitemap
